= Adding search results

:idprefix:
:idseparator: -

:data_table_column_properties_cookbook_url: xref:latest@guides:angular/cookbook/components/interactive-data-view/data-table-column.adoc
:result_diagram_cookbook_url: xref:latest@guides:angular:cookbook/components/group-by-count-diagram/index.adoc

:!sectids:
[#configure-search-results]
== Goal: Configure search results
:sectids:
:sectnums:

Configure the search results to be returned to the user in your search page, after hiting the search button.

[#request-object]
== Response Object
Add additional properties to the OpenAPI specification file `+<feature>-bff.yaml+`, if needed.

.Example:
[source, yml]
----
  <Feature>:
        type: object
        required:
          - 'modificationCount'
          - 'id'
        properties:
          modificationCount:
            type: integer
            format: int32
          id:
            type: integer
            format: int64
          exampleProperty:
            type: string
----

[#columns]
== Columns of Result Data Table
Please define the result columns in your `+<Feature>SearchColumns+` object, located in `+<feature>-search.columns.ts+` file.

.Example:
[subs=+macros]
[source, javascript]
----
  export const FeaturePropertySearchColumns: DataTableColumn[] = [
        {
        columnType: ColumnType.STRING,
        id: 'columnId',
        nameKey: 'FEATURE_PROPERTY_SEARCH.RESULTS.COLUMN_ID',
        filterable: true,
        sortable: true,
        predefinedGroupKeys: [
          'FEATURE_PROPERTY_SEARCH.PREDEFINED_GROUP.DEFAULT',
          'FEATURE_PROPERTY_SEARCH.PREDEFINED_GROUP.EXTENDED',
          'FEATURE_PROPERTY_SEARCH.PREDEFINED_GROUP.FULL',
        ],
      },
  ]
----

Refer to the {data_table_column_properties_cookbook_url}[cookbook for overview of all DataTableColumn properties].

[#translations]
== Translations for Columns with Type `TRANSLATION_KEY`
                                                         
_Adapt in File:_ <feature>-search.selectors.ts
.Example:
[source, javascript]
----
  export const selectResults = createSelector(
    ExampleFeaturePropertySearchSelectors.selectResults,
    (results): RowListGridData[] => {
      return results.map((item) => ({      
        imagePath: '',
        ...item,
        columnId1: item.columnId1
          ? `EXAMPLE_FEATUTRE_PROPERTY_SEARCH.RESULTS.COLUMNID1.${item.columnId1}`
          : '',
      }));
    }
  );
----                                                         
  
[#diagram]
== Result Diagram

* Assign the id of your selected column to `+diagramColumnId+`, which is used as a key in the diagram to show the distribution of data of that column.

_Adapt in File:_ `+<feature>-search.component.ts+`

[source, javascript]
----
    // Please select the column to be displayed in the diagram
    diagramColumnId = 'selectedColumnId';
    diagramColumn$ = this.viewModel$.pipe(
      map(
        (vm) =>
          vm.columns.find((e) => e.id === this.diagramColumnId) as DataTableColumn
      )
    ); 
----

* Adjust the position of the result diagram

If you want to change the position of the result diagram, you can change the layout of the ocx-content-container.

_Adapt in File:_ `+<feature>-search.component.html+`

.vertical layout
[source, html]
----
    <ocx-content-container layout="vertical">
        ...
    </ocx-content-container>
----

.horizontal layout
[source, html]
----
    <ocx-content-container layout="horizontal">
        ...
    </ocx-content-container>
----

The diagram itself is defined through `+<ocx-group-by-count-diagram></ocx-group-by-count-diagram>+` component.
Please refer to the {result_diagram_cookbook_url}[result diagram cookbook] for more adaptations.
