[#types-of-microfrontends-in-onecx]
= Types of microfrontends in OneCX

In OneCX, we have two types of microfrontends, based on how it loads remote module:

 * *WebComponent script*
 * *WebComponent module*

== WebComponent script

When loading content as *WebComponent script*, the remote's JavaScript executed and the custom element `<demo-mfe-app>` is registered globally on `window['demoMfeApp']` namespace 

=== Execution sequence

* When Remote entry option is set as `type` script
    - loadRemoteModule method of module federation is called with `xref:#toLoadRemoteEntryOptionsScript[toLoadRemoteEntryOptions]`
    - Module federation fetches `remoteEntry.js` file from `remoteEntry` URL
    - Registers custom element globally by attaching it to `window` object with the name provided in `remoteName` property
    - Loads shared package by negotiating the version with the host application
    - When technology is `WebComponentScript`, then WebcomponentLoaderModule's component initializes
    - Angular renders `web-component-loader`
    - On `WebcomponentLoaderComponent` initialization, it dynamically creates a custom element node
    - Add app, product and route information to the new element
    - Appends custom element to WebcomponentLoaderComponent


[#toLoadRemoteEntryOptionsScript]
.Example - toLoadRemoteEntryOptions
[source, typescript]
{
    type: 'script'
    remoteName: 'dashboard',
    remoteEntry: 'https://dashboard-host/remoteEntry.js',
    exposedModule: './DashboardComponent'
}

.Example - result in DOM
[source, html]
<app-root>
<router-outlet></router-outlet>
  <web-component-loader> // Angular component
    <dashboard-app> // Custom element
      [Dashboard's HTML]
    </dashboard-app>                               
  </web-component-loader>                          
</router-outlet>
</app-root>

=== WebComponent module

When loading content as *WebComponent module*, exposed content is loaded as *ES module*.

=== Execution sequence:

    - loadRemoteModule method of module federation is called with `xref:#toLoadRemoteEntryOptionsModule[toLoadRemoteEntryOptions]`
    - Module federation fetches `remoteEntry.js` file from `remoteEntry` URL
    - load element as Load as ES module
    - Parse remoteEntry.js and check what is exposed and required and what version are loaded?
    - Extract metadata about shared dependencies and negotiate for the same
    - loads exposed module as javascript
    - When technology is `WebComponentModule`, then WebcomponentLoaderModule's component initializes
    - Angular renders `web-component-loader`
    - On `WebcomponentLoaderComponent` initialization, it dynamically creates a custom element node
    - Add app, product and route information to the new element
    - Appends custom element to WebcomponentLoaderComponent


[#toLoadRemoteEntryOptionsModule]
.Example - toLoadRemoteEntryOptions
[source, typescript]
{
    type: 'module'
    remoteEntry: 'https://dashboard-host/remoteEntry.js',
    exposedModule: './DashboardModule'
}


.Example - result in DOM
[source, html]
<app-root>
  <!-- Shell app -->  
  <router-outlet>
    <!-- This is where the route loads -->    
    <web-component-loader>
      <!-- This is WebcomponentLoaderComponent -->      
      <dashboard-app 
        x-app-id="dashboard-app"
        x-product-name="report"
        x-base-url="/portal/dashboard">
        <div class="dashboard-container">
          <h1>Dashboard</h1>
          <p>Welcome to Dashboard MFE</p>
        </div>        
      </dashboard-app>      
    </web-component-loader>    
  </router-outlet>  
</app-root>