= Migrate to OneCX version 6

:idprefix:
:idseparator: -

:theming_url: xref:angular:cookbook/theming.adoc

[#migration-checklist]
== Migration checklist
[%interactive]
* [ ] <<removed-packages, Remove @onecx/keycloak-auth>>
* [ ] <<removed-packages, Remove @onecx/portal-layout-styles>>
* [ ] <<removed-packages, Remove @onecx/portal-integration-interface>>
* [ ] <<deleted-components, Check deleted components>>
* [ ] <<new-plugin, Add new plugin to webpack config>>
* [ ] <<theme-config, Provide theme configuration for Microfrontends and Remote Components>>
* [ ] <<filter-type, Update FilterType usage>>
* [ ] <<configuration-service, Update ConfigurationService usage>>
* [ ] <<theme-service, Update ThemeService usage>>
* [ ] <<base-url, Replace BASE_URL injection token>>
* [ ] <<angular-in-webpack, Remove `singleton:true` from angular packages in webpack>>
* [ ] <<translation-bootstrap, Move translation related providers to bootstrap.ts for Remote Components>>

[#removed-packages]
== Removed packages
In the version 6 of OneCX the following packages are not longer available:

* *@onecx/keycloak-auth*
* *@onecx/portal-layout-styles*
* *@onecx/portal-integration-interface*

[#deleted-components]
== Check deleted components
Some components will be removed. Please check if you are using following components:


[#removed-from-integration-angular]
=== Removed from @onecx/portal-integration-angular

* portal-footer 
* portal-header
* portal-viewport + 
=> *These components are now in @onecx/shell-core* 

* portal-menu
* portal-menu-horizontal 
* inline-profile +
=> *They are now remote components in onecx-workspace-ui*

* core/initializer/standalone.initializer.ts + 
=>  *Please use standalone mode instead xref:angular:pages:migrations:enable-standalone/index.adoc[Documentation]*

* services/app.menu.service.ts +
=> *If someone wants to load menu item they should create an endpoint in the BFF of the own app and create their own function.*

[#new-plugin]
== Add required plugin to webpack config (will be changed to OneCX plugin)
Since version 6 its required to add the following plugin into the webpack of the Application.

.Webpack plugin snippet
```
const { ModifySourcePlugin, ReplaceOperation } = require('modify-source-webpack-plugin')
...
const modifyPrimeNgPlugin = new ModifySourcePlugin({
  rules: [
    {
      test: (module) => {
        return module.resource && module.resource.includes('primeng')
      },
      operations: [
        new ReplaceOperation(
          'all',
          'document\\.createElement\\(([^)]+)\\)',
          'document.createElementFromPrimeNg({"this": this, "arguments": Array.from(arguments), element: $1})'
        ),
        new ReplaceOperation('all', 'Theme.setLoadedStyleName', '(function(_){})')
      ]
    }
  ]
})
module.exports = {
  ...webpackConfig,
  plugins: [...plugins, modifyPrimeNgPlugin]
}
```

[#theme-config]
== Provide ThemeConfig
Since version 6 of OneCX it is required to add an additional provider to the Microfrontends and Remote Components.

.mfe.remote.module.ts
```
import { provideThemeConfig } from '@onecx/angular-utils'
...
@NgModule({
    providers: [
        provideThemeConfig()
    ]
}) export class MyMfe {}
```

.remote-component.bootstrap.ts
```
import { provideThemeConfig } from '@onecx/angular-utils'

bootstrapRemoteComponent(RemoteComponent, 'my-remote-component', environment.production, [
  provideThemeConfig()
])
```

[#theme-overrides]
=== Provide theme overrides
New theming introduced in version 6 of OneCX is based on PrimeNG theming mechanism. However, in OneCX it is possible to style the content differently per Application. The mechanism that allows that is called theme overrides.

Each Mfe or Remote Component can specify their overrides that will guarantee that certain styles are applied differently than in other applications on the page. Here is an example of how to provide overrides.

```
provideThemeConfig({
  overrides: {
    semantic: {
      extend: {
        onecx: {
          secondaryColor: 'red'
        },
      },
      focusRing: {
        width: '2px',
        style: 'solid',
        color: '{primary.color}',
        offset: '0px',
        shadow: 'none',
      },
    }
  }
})
```

In this example:

* the *secondary color* theme variable is changed
* the *default focus highlight* is changed

More about what and how to override can be found in {theming_url}[theming documentation].

[#filter-type]
== FilterType values changes
Please, make sure to update `FilterType` usage:

* `FilterType.EQUAL` &#8594; `FilterType.EQUALS`
* `FilterType.TRUTHY` &#8594; `FilterType.IS_NOT_EMPTY`

[#configuration-service]
== Check usage of ConfigurationService 
ConfigurationService (@onecx/angular-integration-interface) is now asynchronous. Please check if usage needs to be adapted.

[#theme-service]
== ThemeService removed functionality
ThemeService in version 6 should *only be used to access the currentTheme* via `currentTheme$` property. The following have been removed:

* `baseUrlV1` property
* `getThemeRef` function
* `loadAndApplyTheme` function 
* `apply` function 

Please, make sure that those methods are no longer used.

[#base-url]
== BASE_URL injection token
`BASE_URL` injection token should no longer be used, instead please use `REMOTE_COMPONENT_CONFIG`

[#angular-in-webpack]
== Adjust angular packages in webpack
Make sure that all angular packages *do not have `singleton:true` set in webpack.config.js*. 

[#translation-bootstrap]
== Move translation providers to bootstrap.ts for Remote Components
For each Remote Component translation related providers are required to be defined in the bootstrap.ts instead of the component.ts file.

.remote-component.bootstrap.ts
```
import { bootstrapRemoteComponent } from '@onecx/angular-webcomponents'
import {
  REMOTE_COMPONENT_CONFIG,
  RemoteComponentConfig,
  provideTranslateServiceForRoot
} from '@onecx/angular-remote-components'
import { TranslateLoader } from '@ngx-translate/core'
import { ReplaySubject } from 'rxjs'
import { TRANSLATION_PATH, createTranslateLoader, remoteComponentTranslationPathFactory } from '@onecx/angular-utils'

bootstrapRemoteComponent(RemoteComponent, 'ocx-my-remote-component', environment.production, [
  ...
  { provide: REMOTE_COMPONENT_CONFIG, useValue: new ReplaySubject<RemoteComponentConfig>(1) },
  provideTranslateServiceForRoot({
    isolate: true,
    loader: {
      provide: TranslateLoader,
      useFactory: createTranslateLoader,
      deps: [HttpClient]
    }
  }),
  {
    provide: TRANSLATION_PATH,
    useFactory: (remoteComponentConfig: ReplaySubject<RemoteComponentConfig>) =>
      remoteComponentTranslationPathFactory('assets/i18n/')(remoteComponentConfig),
    multi: true,
    deps: [REMOTE_COMPONENT_CONFIG]
  }
])
```

[#further-considerations]
== Further considerations
[#angular-19-further-changes]
=== Angular 19 changes
Make sure to adjust the Application to the Angular 19 requirements. Based on the implementation there could be changes required to be made to ensure compatibility.

[#primeng-19-further-changes]
=== PrimeNG 19 changes
If the migrated Application uses PrimeNG components, please make sure to adjust the implementation according to the PrimeNG 19 requirements and API changes.
