= Dropdown

:idprefix:
:idseparator: -
:!sectids:
[#goal]
== Goal: Add Dropdown Input
:sectids:
:sectnums:

Add a Dropdown as a search criteria input field for your search page.

NOTE: Please replace all occurences of *exampleEnum* with the actual name in the following code snippets

[#bff]
== OpenAPI specification of search criteria in BFF endpoint

_Adapt in File:_ `+<feature>-bff.yaml+`

[source, yaml]
---- 
    Feature:
      type: object
      properties:
        exampleEnum:
          type: string
          enum:
            - REQUIRED
            - INSTALLED
            - CANCELED
----

[#parameters]
== Search criteria representation in typescript parameters
First, add a new member to the <feature>SearchCriteriasSchema:

_Adapt in File:_ `+<feature>-search.parameters.ts+`

[source, javascript]
----    
    exampleEnum: z
        .string()
        .transform((v) => v as <%= featurePropertyName %>SearchRequestExampleEnum)
        .optional(),
----

[#html]
== HTML input fields for search criteria
Next, add the following code to your formGroup in the html file and adapt by replacing all occurences of `+exampleEnum+` with the actual name which is defined.

_Adapt in File:_ `+<feature>-search.component.html+`

[source, html]
----
    <span class="p-float-label">
        <p-dropdown
              id="exampleEnum"
              formControlName="exampleEnum"
              [options]="(exampleEnum$ | async) ?? []"
              optionLabel="label"
              optionValue="value"
              placeholder="{{ 'YOUR_PRODUCT_SEARCH.CRITERIA.EXAMPLE_ENUM.PLACEHOLDER' | translate }}"
              display="chip"
              [showClear]="true"
        ></p-dropdown>
        <label for="exampleEnum$">{{
            'YOUR_PRODUCT_SEARCH.CRITERIA.EXAMPLE_ENUM.TITLE' | translate
        }}</label>
    </span>
----

[#component]
== Translations
Furthermore, the following needs to be done to have the correct translations displayed:

_Adapt in File:_ `+<feature>-search.component.ts+`

[source, javascript]
----
    import { TranslateService } from '@ngx-translate/core';
    import { enumToDropdownOptions } from '@onecx/angular-accelerator';
    ...

    constructor(
        ...
        private translateService: TranslateService,
        ...
    ) {}
    ...

    exampleEnum$ = enumToDropdownOptions(
        this.translateService,
        <%= featurePropertyName %>SearchRequestExampleEnum,
        'YOUR_PRODUCT_SEARCH.CRITERIA.EXAMPLE_ENUM.OPTIONS.',
    );
----

NOTE: Don't forget to add the translations to your *de.json* and *en.json*.

