= Adding search criteria

:idprefix:
:idseparator: -
:!sectids:
[#configure-search-criteria]
== Goal: Configure search criteria
:sectids:
:sectnums:

Configure the search criteria in openAPI specification of BFF endpoint. Define parameters in typescript corresponding to search criteria in openAPI. Add HTML components, enabling the user to provide search criteria.

[#request-object]
== OpenAPI specification of search criteria in BFF endpoint
Add the search criteria to the `+<feature>-bff.yaml+` file to the `+properties+` section.

Search criteria examples:

* Text criteria `+exampleString+` (replace with the name of your search criteria of type string):

[source, yml]
----
Search<Feature>Request:
      type: object
      properties:
        exampleString:
          type: string
        # Add additional properties here
----

* xref:ngrx/cookbook/adding-search-criteria/calendar.adoc[Calendar criteria]
* xref:ngrx/cookbook/adding-search-criteria/dropdown.adoc[Dropdown criteria]
* xref:ngrx/cookbook/adding-search-criteria/multiselect.adoc[MultiSelect criteria]
* xref:ngrx/cookbook/adding-search-criteria/autocomplete/autocomplete.adoc[AutoComplete criteria]

[#parameters]
== Search criteria representation in typescript parameters
Please define the members for your `+<feature>SearchCriteriaSchema+` in file `+<feature>-search.parameters.ts+`.

While defining search parameters note that:

* keys *need* to match the keys from your OpenAPIs SearchCriteria Object
* always start with `+z.string()+`
* when required, you can use `+.transform()+` to extend the validation

Parameter examples:

* Text parameter `+exampleString+` (replace with the name of your search criteria of type string):

[source, typescript]
----
export const featureSearchCriteriasSchema = z.object({
    exampleString: z.string().optional(),
    // Add additional parameters here
} satisfies Partial<Record<keyof SearchPropertiesRequest, ZodTypeAny>>);
----

* xref:ngrx/cookbook/adding-search-criteria/calendar.adoc[Calendar parameter]
* xref:ngrx/cookbook/adding-search-criteria/dropdown.adoc[Dropdown parameter]
* xref:ngrx/cookbook/adding-search-criteria/multiselect.adoc[MultiSelect parameter]
* xref:ngrx/cookbook/adding-search-criteria/autocomplete/autocomplete.adoc[AutoComplete parameter]


[#html]
== HTML input fields for search criteria
You need to specify the HTML components, into which the search criteria can be entered or selected by the user.

* The input fields must be added
** `+formControlName+` must match to your SearchCriteria model

_Adapt in File:_ `+<feature>-search.component.html+`

[subs=+macros]
[source, html]
----
 <form [formGroup]="criteriaGroup">
      <div class="grid mt-0 p-fluid">
        <div class="col-12 md:col-3">
          <span class="p-float-label">
           // PLACE YOUR INPUT FIELD HERE
          </span>
        </div>
        ...
----

Input field examples:

* Text input field
** Remove `+// PLACE YOUR INPUT FIELD HERE+` and paste the following code
** Adapt `+id+`, `+formControlName+`, `+ngModel+` and `+for+` as well as the labels translation key

[source, html]
----
    <input
      id="id"
      pInputText
      type="text"
      formControlName="id"
      class="p-inputtext p-component"
    />
    <label for="id">{{
      'YOUR_PRODUCT.CRITERIA.ID' | translate
    }}</label>
----

* xref:ngrx/cookbook/adding-search-criteria/calendar.adoc[Calendar input field]
* xref:ngrx/cookbook/adding-search-criteria/dropdown.adoc[Dropdown input field]
* xref:ngrx/cookbook/adding-search-criteria/multiselect.adoc[MultiSelect input field]
* xref:ngrx/cookbook/adding-search-criteria/autocomplete/autocomplete.adoc[AutoComplete input field]
